### ISSUE TITLE
color_models doesn't accommodate wide gamut adjustments to Flutter's Color

### ISSUE THREAD

**Issue by gaaclarke** [james-alex/color_models#9]
Hi @james-alex, the Color class is changing in Flutter and this package is blocking that change.  There are new floating point accessors coming in.

You can see the design doc here: https://docs.google.com/document/d/1JaJg34uB7bVssr3oyS-QLe2FlZHUIHcR6aG83JlKwak/edit
You can also see the PR that got reverted since it broke this package: https://github.com/flutter/engine/pull/54737
Here is the related issue: https://github.com/flutter/flutter/issues/127855

I'll queue up a change for you.  You can reach me on discord (name gaaclarke) if you want to reach out on chat.

**Comment by lukemmtt** [comment]
FYI, after upgrading my project to the new stable release Flutter 3.27.0, this issue resulted in build errors—thus, a new release of color_models & flutter_color_models (incorporating https://github.com/james-alex/color_models/pull/10 or similar) is needed for compatibility going forward.

In case it might help anyone in the meantime, I resolved my project's build errors with a dependency override pointing to the fixes proposed in this PR (but substituting with my own fork):

```yaml
dependencies:
  color_models:
    git:
      url: https://github.com/gaaclarke/color_models.git
      ref: wide-gamut
      path: color_models
  flutter_color_models:
    git:
      url: https://github.com/gaaclarke/color_models.git
      ref: wide-gamut
      path: flutter_color_models
      
dependency_overrides:
  color_models:
    git:
      url: https://github.com/gaaclarke/color_models.git
      ref: wide-gamut
      path: color_models
  flutter_color_models:
    git:
      url: https://github.com/gaaclarke/color_models.git
      ref: wide-gamut
      path: flutter_color_models
```

Thank you @gaaclarke for the fixes 🙏🏻
